### ISSUE TITLE
Add new security patch

### ISSUE THREAD

**Issue by yezz123** [htr-tech/nexphisher#51]
Security patch for phishing and Update the Pages that used to phish ✌

**Comment by htr-tech** [comment]
sure .. i am looking for contributor who can develop / fix phishing pages

**Comment by yezz123** [comment]
I suggest to check that one 👇
https://github.com/yezz123/Phisher/tree/master/sites

**Comment by htr-tech** [comment]
@yezz123 okey .. i will surely check .... :)

**Comment by graysuit** [comment]
@htr-tech 
The reason why mostly phishing pages get broken is because they depend on online resources.
If online resources get changed/removed, things would get broken in phishing pages.
Even if you fix it, after a time it would get broken again.

Its big problem also found in popular phishing tools as well like above:
https://github.com/DarkSecDevelopers/HiddenEye-Legacy/issues/569

And that's why they are now re-coding it:
https://github.com/Open-Security-Group-OSG/HiddenEyeReborn

So final bandage to this headache is just to make pages offline including images,icon,css etc.
